package com.donkeykong.models;

public enum Estado {
    //enumrera todos os estados do mario
    PARADO_ESQUERDA, PARADO_DIREITA, CORRENDO_DIREITA, CORRENDO_ESQUERDA, ESCALANDO, PULANDO_ESQUERDA, PULANDO_DIREITA, MARTELO_ESQUERDA, MARTELO_DIREITA
}
